TheWall/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.loginreg.urls', namespace='user')),
    url(r'^dashboard', include('apps.dashboard.urls', namespace='wall'))
]

apps/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'create/post$', views.create_post),
    url(r'create/comment/(?P<post_id>\d+)$', views.create_comment),
]

apps/loginreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^try/(?P<rType>\d+)$', views.logreg),
    url(r'^logout$', views.log_out),
    url(r'^pw_change$', views.change_pw),
    url(r'^users$', views.ListUsers.as_view()),
    url(r'^user/edit/(?P<pk>\d+)$', views.UpdateUser.as_view(), name='edit'),
    url(r'^user/show/(?P<pk>\d+)$', views.DetailUser.as_view(), name='show')
]

apps/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..loginreg.models import WallUser
from django.db import models
from datetime import datetime, timedelta
from django.utils import timezone
from django.utils.timesince import timesince
from django.utils.translation import ugettext_lazy as _
from shared_util.utc import utc

# 15 minutes (in seconds)
EDIT_TIME_ALLOWED = 60 * 60

# Create your models here.
class Post(models.Model):
    content = models.TextField()
    author = models.ForeignKey(WallUser, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
    

    def time_since_updated(self):
        return datetime.now(utc) - self.updated_at

    def time_since_updated_format(self):
        hours, rem = divmod(self.time_since_updated().total_seconds(), 3600)
        minutes, seconds = divmod(rem, 60)
        return '%s:%s:%s' % (int(hours), int(minutes), int(seconds))

    def can_edit(self):
        return self.time_since_updated().total_seconds() < EDIT_TIME_ALLOWED

    def __unicode__(self):
        return "Post Object {} created by {}".format(self.id, self.author.first_name)
   
class Comment(models.Model):
    content = models.TextField()
    author = models.ForeignKey(WallUser, null=True, on_delete=models.SET_NULL)
    rel_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

apps/dashboard/forms.py
from django.forms import ModelForm
from .models import Post, Comment
from .fields import PostField, CommentField

class CreatePostForm(ModelForm):
    content = PostField()
    class Meta:
        model = Post
        fields = ['content'] 

class CreateCommentForm(ModelForm):
    content = CommentField()
    class Meta:
        model = Comment
        fields = ['content']

apps/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from .forms import CreatePostForm, CreateCommentForm
from .models import Post, Comment
from .view_helpers import get_template_data, initialize_context

TEMPLATE_URL = 'dashboard/index.html'

MAIN_CONTEXT = initialize_context()

# Create your views here.
@login_required
def index(req):
    #TODO(dev): we are double querying here, OPTIMZE THIS
    MAIN_CONTEXT = initialize_context()
    
    return render(req, TEMPLATE_URL, MAIN_CONTEXT)

def create_post(req):
    submitted = CreatePostForm(req.POST)
    if submitted.is_valid():
        author = req.user
        new_post = submitted.save(commit=False)
        new_post.author = author
        new_post.save()        
        return redirect('/dashboard')

    MAIN_CONTEXT['forms']['post'] = submitted
    MAIN_CONTEXT["data"] = get_template_data()
    return render(req, TEMPLATE_URL, MAIN_CONTEXT)

def create_comment(req, post_id):
    submitted_comment = CreateCommentForm(req.POST)
    if submitted_comment.is_valid():
        user = req.user
        post = Post.objects.get(id=post_id)
        new_comment = submitted_comment.save(commit=False)
        new_comment.author = user
        new_comment.rel_post = post
        new_comment.save()
        return redirect('/dashboard')

    MAIN_CONTEXT['forms']['bound_comment_form'] = submitted_comment
    MAIN_CONTEXT['bound_post'] = int(post_id)
    MAIN_CONTEXT["data"] = get_template_data()
    return render(req, TEMPLATE_URL, MAIN_CONTEXT)

apps/dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
       {% load staticfiles %}
		<link rel="stylesheet" href="{% static '/css/main.css' %}" media="screen">
		<link rel="stylesheet" href="{% static '/dashboard/css/dashboard.css' %}" media="screen">
        
    </head>
    <body>
        
        {% include "templates/nav.html" %}
        
        <div class="container">
            <h2>Add some terrific CONTENT to the wall</h2>
            <form action='/dashboard/create/post' method="POST">{% csrf_token %}
                {% for field in forms.post %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <p class="form-error">{{ error }}</p>
                    {% endfor %}
                {% endif %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <input type="submit" value="Post">
            </form>
            <hr>
            {% for post in data.posts %}
            <div class="post">
                <h5><a href="{% url 'user:show' post.author.id %}">{{ post.author.first_name}} {{post.author.last_name }}</a> posted:</h5>
                <p class=post-content>{{ post.content }}</p>
                <span>{{ post.created_at }} ({{ post.time_since_updated_format }} ago)</span>
                <form action='/dashboard/create/comment/{{ post.id }}' method="POST">{% csrf_token %}
                    {% if post.id == bound_post %}
                        {% for field in forms.bound_comment_form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p class="form-error">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                        {% endfor %}
                    {% else %}
                        {% for field in forms.comment %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                        {% endfor %}
                    {% endif %}
                    <input type="submit" value="Comment">
                    <!--<NOTE>DISABLING EDIT BUTTON FOR NOW</NOTE>-->
                    <!--{% if post.can_edit and post.author.id == user.id %}
                        <button can-edit='false' class='edit-post-btn'>Switch to Edit</button>
                    {% endif %}-->
                </form>
            </div>
                {% for comment in data.comments %}
                {% if post.id == comment.rel_post.id %}
                    <div class="comment">
                        <h6>{{ comment.author.first_name}} {{comment.author.last_name }} commented:</h6>
                        <p class=comment-content>{{ comment.content }}</p>
                        <span>{{ comment.created_at }}</span>
                    </div>
                {% endif %}
                {% endfor %}
            {% endfor %}
        </div>

    </body>
    <!--<script
        src="https://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
        crossorigin="anonymous"></script>
    <script src="{% static '/dashboard/js/dashboard.js' %}"></script>-->
</html>